### PR TITLE
Added AUTHORS_NG.rst

### PR DESCRIPTION
**Pull request by viniarck**
In our last meeting, it was recommended to add a new authors file for Kytos-ng. I've added a section describing our team, authors, and contributors we've had in version 2022.1, I suppose this way it makes clearer who currently is part of the team maintaining Kytos-ng. If you have any other suggestions or want to change any other personal detail, please let us know.

### CODE REVIEW

**Review by ajoaoff — COMMENTED** [review]
Shouldn't Daniela and Luis be included as contributors?

**Comment by viniarck** [comment]
> Shouldn't Daniela and Luis be included as contributors?

Included here https://github.com/kytos-ng/kytos/pull/170/commits/7b156e979896917da40e444ad4a5ca2db70c411d

**Review by ajoaoff — APPROVED** [review]
LGTM

**Comment by viniarck** [comment]
> LGTM

Appreciated your review, Antonio.

**Pull request merged**
