### PR TITLE
[Feature] ThreadPoolExecutor for `listen_to` events handlers

### LINKED ISSUE #148: `listen_to` decorator contributes to high memory usage when there are hundreds of events / sec
The `listen_to` decorator is spawning a new thread when calling the handler. This approach can be problematic in terms of memory resource management since Threads aren't that lightweight, especially when it's being used as a one to one mapping with a `KytosEven`. This problem can be observed as you scale the number of events to hundreds / sec: 

plot1_t0_q0_1

Potential solutions (in order of implementation cost based on the architecture we currently have), all of them could work reliably though considering the trade offs: 

1) Thread pool and queueing
2) `async listen_to`
3) Another message broker

### PR DESCRIPTION
**Pull request by viniarck**
Fixes #148 

- Added a `ThreadPoolExecutor` for the `listen_to` decorator to enhance memory management and increase the overall responsiveness by making use of queue buffering for producers. 

### Description of the change

- Added on `kytosd` a `--thread_pool_max_workers` configuration option to control the size of the thread pool. 

- As you can see in the results below, if the producers start overwhelmingly create events, `kytosd` doesn't have an upper bound limit in terms of threads, and executions can start piling up which in turn can lead to a lot of memory usage, and if producers won't stop, this can further lead to starvation problems like unresponsiveness, in this picture below, there are 700+ events/sec using these two stress tests (throw-away) NApps [ping](https://www.github.com/viniarck/kytos_ping) and [pong](https://www.github.com/viniarck/kytos_pong): 

thread_pool_res

- The optimal number of threads depends on how many producers, consumers, events, locks, IO interruptions being used and the underlying capacity of CPU/MEM of the host runtime and OS. I've run several benchmark test (in a scenario with 700+ events/sec) to try to provide a reasonable default value that should be good for most of the cases, and as you can see in the figure below, based on an idea that @italovalcy has also suggested to measure delay response times of the events 256 threads has demonstrated to be good enough, notice that with `32`  threads the response times and overall statistics were better, probably because of fewer context switching for this case in particular, but considering a case where several NApps are running, slower methods, and also if there are a significant number of locks, it would be handy to have some extra threads ready in the pool, so, that's why I believe that having a default of `256` threads despite slightly worse time diff responsiveness for some events in case when it's overwhelmed, it would provide a better experience out of the box, and then operators can tune accordingly based on what they have.

ping_pong_time_diff_results

- Notice that this isn't also a completely bullet proof solution, but it'll result in less memory usage and more stability in terms of `listen_to` handlers executions, and if there are still producers overwhelmingly queuing too much the memory usage can still keep increasing although at a way slower pace than the unbounded case that we used to have, as the queue will hold that in memory, however, as consumers start doing their job it should eventually normalize. 

**Future work/improvements**: 

- In the same way the we could have dedicated `queues` for events, we could have dedicated or high priority `ThreadPoolExecutor` for different NApps, let's say `of_core` could have higher priority than other less critical NApps.  
- `async alisten_to` version of `listen_to` for NApps that are heavily using IO and waiting a lot (when this pattern use case arises)
- Invest time and effort to migrate to a specific message broker like RabbitMQ but that has a high effort considering all the objects being passed around, architecture, infrastructure and so on, the team is aware of this, but just mentioning here again, for the record, for future readers of this PR.

### CODE REVIEW

**Comment by viniarck** [comment]
Settings as a draft. I'm collecting more executions benchmark results, and I'll also push some unit tests.

**Comment by viniarck** [comment]
> Settings as a draft. I'm collecting more executions benchmark results, and I'll also push some unit tests.

It's ready for review again, I've updated the description, ran more tests to make a decision of the default value, and pushed the tests.

**Comment by italovalcy** [comment]
> * The optimal number of threads depends on how many producers, consumers, events, locks, IO interruptions being used and the underlying capacity of CPU/MEM of the host runtime and OS. I've run several benchmark test (in a scenario with 700+ events/sec) to try to provide a reasonable default value that should be good for most of the cases, and as you can see in the figure below, based on an idea that @italovalcy has also suggested to measure delay response times of the events 256 threads has demonstrated to be good enough, notice that with `32`  threads the response times and overall statistics were better, probably because of fewer context switching for this case in particular, but considering a case where several NApps are running, slower methods, and also if there are a significant number of locks, it would be handy to have some extra threads ready in the pool, so, that's why I believe that having a default of `256` threads despite slightly worse time diff responsiveness for some events in case when it's overwhelmed, it would provide a better experience out of the box, and then operators can tune accordingly based on the number of events they have in place.

What is the difference between graphs in the left and right columns, @viniarck ? Are they a 2nd repetition? The rows are clearly representing different scenarios (256 threads, 128 threads, 32 threads and no thread pool), but the columns aren't clear.

**Review by italovalcy — APPROVED** [review]
Very interesting solution, @viniarck. Thank you for the benchmark, it is very well documented and reproducible. I've also tested the solution in a physical environment with 6 real switches, 12 links and 300 EVCs (600 flows) and it works pretty well. The choice for 256 is also well structured, so for me we are ready to roll it out.

**Review by ajoaoff — APPROVED** [review]

**Comment by viniarck** [comment]
> > * The optimal number of threads depends on how many producers, consumers, events, locks, IO interruptions being used and the underlying capacity of CPU/MEM of the host runtime and OS. I've run several benchmark test (in a scenario with 700+ events/sec) to try to provide a reasonable default value that should be good for most of the cases, and as you can see in the figure below, based on an idea that @italovalcy has also suggested to measure delay response times of the events 256 threads has demonstrated to be good enough, notice that with `32`  threads the response times and overall statistics were better, probably because of fewer context switching for this case in particular, but considering a case where several NApps are running, slower methods, and also if there are a significant number of locks, it would be handy to have some extra threads ready in the pool, so, that's why I believe that having a default of `256` threads despite slightly worse time diff responsiveness for some events in case when it's overwhelmed, it would provide a better experience out of the box, and then operators can tune accordingly based on the number of events they have in place.
> 
> What is the difference between graphs in the left and right columns, @viniarck ? Are they a 2nd repetition? The rows are clearly representing different scenarios (256 threads, 128 threads, 32 threads and no thread pool), but the columns aren't clear.

Yes. It's repeated execution to confirm similar expected time diff results (although each exec had a higher number of events). In the future, it might be worth scripting this.

**Comment by viniarck** [comment]
> Very interesting solution, @viniarck. Thank you for the benchmark, it is very well documented and reproducible. I've also tested the solution in a physical environment with 6 real switches, 12 links and 300 EVCs (600 flows) and it works pretty well. The choice for 256 is also well structured, so for me we are ready to roll it out.

Awesome @italovalcy, appreciated your help also trying this branch out in this scenario, glad to hear it worked well in that case too.

**Comment by viniarck** [comment]
thanks for reviewing @italovalcy and @ajoaoff

**Pull request merged**
