### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ajoaoff**
Update README for kytos-ng:

* Replace references to kytos project for kytos-ng

### CODE REVIEW

**Review by ajoaoff — COMMENTED** [review]
The `Get help` section should be removed or are going to create some kind of communication channel to put here? @italovalcy @rmotitsuki @viniarck

**Comment by viniarck** [comment]
> The `Get help` section should be removed or are going to create some kind of communication channel to put here? @italovalcy @rmotitsuki @viniarck

@ajoaoff, good point, @jab1982 might have more info or plans about potential future communication channels, maybe at least we could have `dev@amlight.net` mentioned as a point of contact?

**Comment by viniarck** [comment]
@ajoaoff The main changes looks good to me, thanks for updating the readme, I've noticed in the rendered readme [directly on GitHub on this PR branch](https://github.com/ajoaoff/kytos/tree/update-readme), there are some links that apparently are broken highlighted in yellow

2022-01-13-103738_936x775_scrot

**Comment by jab1982** [comment]
Let's create an alias ***@***.*** Don't use ***@***.***,
that's internal. Also, we have a Slack workgroup for Kytos-ng.

**Review by italovalcy — APPROVED** [review]

**Pull request merged**
